all: validate

validate:
	@go build ./...
	@go vet ./cmd/...
	@go vet ./lib/...
	@go tool vet -shadow cmd/dustdevil/
	@go tool vet -shadow lib/dustdevil/
	@golint ./cmd/...
	@golint ./lib/...
	@ineffassign cmd/dustdevil/
	@ineffassign lib/dustdevil/
